#!/usr/bin/env bash
# GUI smoke (headless): locate the built PDF4QT Viewer, verify it starts
# under QT_QPA_PLATFORM=offscreen (falling back to xvfb-run when the
# platform plugin refuses offscreen), open the deterministic RTL fixture
# (src/tests/fixtures/gui-rtl.pdf) and confirm the event loop is alive,
# then terminate it cleanly. Never hangs.
#
# Exit codes:
#   0  all checks passed
#   1  a check failed (startup crash, fixture missing/hash mismatch, ...)
#   2  Viewer binary not found -> GUI not built (ALBDF_BUILD_GUI=ON)
#
# Usage:
#   bash src/tests/gui-smoke.sh                     # defaults below
#   bash src/tests/gui-smoke.sh [--viewer PATH] [--fixture PATH]
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

VIEWER=""
FIXTURE="${SCRIPT_DIR}/fixtures/gui-rtl.pdf"
# sha256 of the committed deterministic RTL fixture (سلام with lam-alef
# ligature, generated by: albdf add-text fixtures/blank.pdf ... --rtl --lang ar)
FIXTURE_SHA256="db787c3005a4a3275ecbbda5da0458d5fd78ad5345b465e37da9577f258f7006"
# how long the viewer must stay alive after opening the fixture (seconds)
SMOKE_SECONDS="${GUI_SMOKE_SECONDS:-8}"

while [ $# -gt 0 ]; do
    case "$1" in
        --viewer)  VIEWER="$2"; shift 2 ;;
        --fixture) FIXTURE="$2"; shift 2 ;;
        *) echo "usage: $0 [--viewer PATH] [--fixture PATH]" >&2; exit 7 ;;
    esac
done

fail() { echo "FAIL: $*" >&2; exit 1; }

# --- (a) locate the built Viewer binary -------------------------------------
if [ -z "${VIEWER}" ]; then
    for c in \
        "${REPO_ROOT}/src/build-gui/bin/Pdf4QtViewer" \
        "${REPO_ROOT}/src/build/bin/Pdf4QtViewer" \
        "${REPO_ROOT}/build-gui/bin/Pdf4QtViewer" \
        "${REPO_ROOT}/build/bin/Pdf4QtViewer"
    do
        if [ -x "$c" ]; then VIEWER="$c"; break; fi
    done
fi

if [ -z "${VIEWER}" ] || [ ! -x "${VIEWER}" ]; then
    echo "FAIL: Viewer not built — run with ALBDF_BUILD_GUI=ON" >&2
    echo "      (expected binary: src/build-gui/bin/Pdf4QtViewer)" >&2
    exit 2
fi
echo "OK: viewer = ${VIEWER}"

# --- fixture sanity: exists and is the committed deterministic RTL PDF -------
if [ ! -f "${FIXTURE}" ]; then
    fail "RTL fixture not found: ${FIXTURE}"
fi
actual_sha="$(sha256sum "${FIXTURE}" | awk '{print $1}')"
if [ "${actual_sha}" != "${FIXTURE_SHA256}" ]; then
    fail "RTL fixture hash mismatch: got ${actual_sha}, expected ${FIXTURE_SHA256} (regenerate with add-text --rtl --lang ar, see src/tests/AGENT.md)"
fi
echo "OK: fixture = ${FIXTURE} (${actual_sha})"

# --- (b)+(c) startup smoke: open the fixture, stay alive, exit cleanly -------
# The viewer runs an event loop (no --exit flag), so we run it under a
# timeout: alive after SMOKE_SECONDS => it started and opened the document;
# we then SIGTERM it and treat a clean termination as success.
run_smoke() {
    # $1 = platform mode: "offscreen" (direct run with QT_QPA_PLATFORM=offscreen)
    #                     or "xvfb" (xvfb-run wrapper, offscreen unset so the
    #                     app can use xcb on the virtual display)
    local mode="$1" log
    log="$(mktemp)"

    if [ "${mode}" = "xvfb" ]; then
        env -u QT_QPA_PLATFORM xvfb-run -a "${VIEWER}" "${FIXTURE}" >"${log}" 2>&1 &
    else
        QT_QPA_PLATFORM=offscreen "${VIEWER}" "${FIXTURE}" >"${log}" 2>&1 &
    fi
    local pid=$!

    local alive=0
    for _ in $(seq 1 "${SMOKE_SECONDS}"); do
        if ! kill -0 "${pid}" 2>/dev/null; then alive=0; break; fi
        alive=1
        sleep 1
    done

    if [ "${alive}" -eq 1 ]; then
        # still running => startup OK; terminate cleanly
        kill -TERM "${pid}" 2>/dev/null
        wait "${pid}" 2>/dev/null
        echo "OK: [${mode}] viewer stayed alive ${SMOKE_SECONDS}s with the RTL fixture open and exited cleanly on SIGTERM"
        return 0
    fi

    wait "${pid}" 2>/dev/null
    local code=$?
    if [ "${code}" -eq 0 ]; then
        echo "OK: [${mode}] viewer opened the RTL fixture and exited cleanly (code 0)"
        return 0
    fi

    echo "WARN: [${mode}] viewer exited early with code ${code}; stderr follows:" >&2
    sed 's/^/      /' "${log}" >&2
    return 1
}

# 0) --help must work headlessly (also proves the binary runs at all).
#    A viewer whose platform plugin refuses offscreen fails here too, so
#    fall back to xvfb-run before declaring the binary unrunnable.
help_platform="offscreen"
if ! QT_QPA_PLATFORM=offscreen "${VIEWER}" --help >/dev/null 2>&1; then
    if command -v xvfb-run >/dev/null 2>&1 && xvfb-run -a "${VIEWER}" --help >/dev/null 2>&1; then
        help_platform="xvfb"
    else
        fail "'${VIEWER} --help' failed under both offscreen and xvfb-run — binary is not runnable"
    fi
fi
echo "OK: --help exits 0 (${help_platform})"

# 1) try offscreen first
if run_smoke "offscreen"; then
    exit 0
fi

# 2) offscreen refused/failed -> fall back to xvfb-run if available
if command -v xvfb-run >/dev/null 2>&1; then
    echo "NOTE: offscreen platform unavailable for the viewer; retrying under xvfb-run"
    if run_smoke "xvfb"; then
        exit 0
    fi
    fail "viewer crashed under both offscreen and xvfb-run"
else
    fail "offscreen platform failed and xvfb-run is not installed (apt install xvfb)"
fi
