// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (c) 2026 pdfedit contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// This file is part of the pdfedit project, a fork of PDF4QT (MIT).
// The upstream PDF4QT portions remain under the MIT License; see the
// upstream copyright headers and the LICENSE file.

// Golden-image regression harness.
//
// Renders every fixture in src/tests/fixtures with PdfTool render
// (72 dpi, PNG, offscreen) and compares the SHA-256 of each rendered page
// against the committed golden files in src/tests/golden/. The golden files
// for test-baseline.pdf are the pre-fork reference recorded in
// docs/research/baseline-upstream.md; the other goldens are fork-anchored
// (generated by the same renderer at fork time and committed as regression
// anchors). A mismatch means the renderer output changed and must be
// investigated - do NOT regenerate goldens blindly.
//
// Paths are injected at build time via PDFEDIT_TESTS_DIR.

#include <QCryptographicHash>
#include <QDir>
#include <QFile>
#include <QImage>
#include <QProcess>
#include <QProcessEnvironment>
#include <QTemporaryDir>

#include <QtTest>

class GoldenTest : public QObject
{
    Q_OBJECT

private slots:
    void golden_data();
    void golden();
    void fixtureRegistryConsistency();

private:
    static QString testsDir();
    static QString pdfToolPath();
    static QByteArray sha256OfFile(const QString& path, bool* ok);
};

QString GoldenTest::testsDir()
{
    return QString::fromUtf8(PDFEDIT_TESTS_DIR);
}

QString GoldenTest::pdfToolPath()
{
    // PdfTool is built into the same runtime output directory as this test.
    return QCoreApplication::applicationDirPath() + QStringLiteral("/PdfTool");
}

QByteArray GoldenTest::sha256OfFile(const QString& path, bool* ok)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly))
    {
        *ok = false;
        return QByteArray();
    }
    *ok = true;
    return QCryptographicHash::hash(file.readAll(), QCryptographicHash::Sha256).toHex();
}

void GoldenTest::golden_data()
{
    QTest::addColumn<QString>("fixtureName"); // e.g. "multipage.pdf"
    QTest::addColumn<int>("pageCount");

    // The fixture corpus lives in src/tests/fixtures. Page counts must match
    // the committed fixtures (info command output); update deliberately.
    QTest::newRow("test-baseline") << QStringLiteral("test-baseline.pdf") << 2;
    QTest::newRow("multipage") << QStringLiteral("multipage.pdf") << 5;
    QTest::newRow("image-doc") << QStringLiteral("image-doc.pdf") << 2;
    QTest::newRow("overlap-text") << QStringLiteral("overlap-text.pdf") << 1;
}

void GoldenTest::golden()
{
    QFETCH(QString, fixtureName);
    QFETCH(int, pageCount);

    const QString fixturePath = testsDir() + QStringLiteral("/fixtures/") + fixtureName;
    QVERIFY2(QFile::exists(fixturePath), qPrintable(QStringLiteral("Fixture missing: %1").arg(fixturePath)));

    const QString stem = fixtureName.left(fixtureName.size() - 4); // strip ".pdf"
    const QString goldenDir = testsDir() + QStringLiteral("/golden/");

    const QString toolPath = pdfToolPath();
    QVERIFY2(QFile::exists(toolPath), qPrintable(QStringLiteral("PdfTool binary missing: %1").arg(toolPath)));

    QTemporaryDir tmpDir;
    QVERIFY(tmpDir.isValid());

    QProcess process;
    QProcessEnvironment env = QProcessEnvironment::systemEnvironment();
    env.insert(QStringLiteral("QT_QPA_PLATFORM"), QStringLiteral("offscreen"));
    process.setProcessEnvironment(env);
    process.setProcessChannelMode(QProcess::SeparateChannels);

    const QStringList arguments = {QStringLiteral("render"),
                                   fixturePath,
                                   QStringLiteral("--page-first"),
                                   QStringLiteral("1"),
                                   QStringLiteral("--page-last"),
                                   QString::number(pageCount),
                                   QStringLiteral("--image-format"),
                                   QStringLiteral("png"),
                                   QStringLiteral("--image-res-dpi"),
                                   QStringLiteral("72"),
                                   QStringLiteral("--image-output-dir"),
                                   tmpDir.path()};

    process.start(toolPath, arguments);
    QVERIFY2(process.waitForStarted(), "PdfTool render did not start");
    QVERIFY2(process.waitForFinished(180000), "PdfTool render timed out");
    const QString stderrText = QString::fromUtf8(process.readAllStandardError());
    QVERIFY2(process.exitStatus() == QProcess::NormalExit && process.exitCode() == 0,
             qPrintable(QStringLiteral("PdfTool render failed (exit %1): %2").arg(process.exitCode()).arg(stderrText)));

    for (int page = 1; page <= pageCount; ++page)
    {
        const QString renderedPath = tmpDir.path() + QStringLiteral("/Image_%1.png").arg(page);
        const QString goldenPath = goldenDir + stem + QStringLiteral("_Image_%1.png").arg(page);

        QVERIFY2(QFile::exists(renderedPath),
                 qPrintable(QStringLiteral("Rendered page missing: %1").arg(renderedPath)));
        QVERIFY2(
            QFile::exists(goldenPath),
            qPrintable(QStringLiteral(
                           "Golden missing: %1 (regenerate via src/tests/scripts/ generators + render, then commit)")
                           .arg(goldenPath)));

        bool renderOk = false;
        bool goldenOk = false;
        const QByteArray renderHash = sha256OfFile(renderedPath, &renderOk);
        const QByteArray goldenHash = sha256OfFile(goldenPath, &goldenOk);
        QVERIFY(renderOk);
        QVERIFY(goldenOk);

        // Also verify the render is a valid PNG with the expected page size.
        QImage image(renderedPath);
        QVERIFY2(!image.isNull(),
                 qPrintable(QStringLiteral("Rendered file is not a decodable PNG: %1").arg(renderedPath)));

        qInfo().noquote() << QStringLiteral("[golden] %1 page %2  sha256 %3  %4x%5")
                                 .arg(fixtureName)
                                 .arg(page)
                                 .arg(QString::fromLatin1(renderHash))
                                 .arg(image.width())
                                 .arg(image.height());

        QVERIFY2(renderHash == goldenHash,
                 qPrintable(QStringLiteral("GOLDEN MISMATCH for %1 page %2:\n"
                                           "  rendered: %3 (%4)\n"
                                           "  golden:   %5 (%6)\n"
                                           "Do NOT update the golden - investigate the render diff.")
                                .arg(fixtureName)
                                .arg(page)
                                .arg(QString::fromLatin1(renderHash), renderedPath)
                                .arg(QString::fromLatin1(goldenHash), goldenPath)));
    }
}

void GoldenTest::fixtureRegistryConsistency()
{
    // Every golden file must correspond to a registered fixture+page, so a
    // stale golden (e.g. after a fixture was removed) is caught.
    const QDir goldenDir(testsDir() + QStringLiteral("/golden"));
    const QStringList goldenFiles = goldenDir.entryList(QStringList() << QStringLiteral("*_Image_*.png"), QDir::Files);
    QVERIFY(!goldenFiles.isEmpty());

    const QStringList fixtures = {QStringLiteral("test-baseline.pdf"),
                                  QStringLiteral("multipage.pdf"),
                                  QStringLiteral("image-doc.pdf"),
                                  QStringLiteral("overlap-text.pdf")};

    int expectedGoldenCount = 0;
    for (const QString& fixture : fixtures)
    {
        const QString stem = fixture.left(fixture.size() - 4);
        const QString fixturePath = testsDir() + QStringLiteral("/fixtures/") + fixture;
        QVERIFY2(QFile::exists(fixturePath),
                 qPrintable(QStringLiteral("Registered fixture missing: %1").arg(fixturePath)));

        const int count =
            goldenDir.entryList(QStringList() << stem + QStringLiteral("_Image_*.png"), QDir::Files).size();
        QVERIFY2(count > 0, qPrintable(QStringLiteral("No goldens for fixture %1").arg(fixture)));
        expectedGoldenCount += count;
    }

    QCOMPARE(goldenFiles.size(), expectedGoldenCount);
}

// QTEST_GUILESS_MAIN instantiates a QCoreApplication so that
// QCoreApplication::applicationDirPath() resolves the PdfTool binary path
// (QTEST_APPLESS_MAIN left it empty -> tool lookup failed).
QTEST_GUILESS_MAIN(GoldenTest)

#include "tst_goldentest.moc"
